#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime environment changes to make the snap work here.  You may also insert security confinement/deprecation/obsoletion notice of the snap here.

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

declare \
    launcher_title='The (UNOFFICIAL) GNU nano Snap Helper'

# Use real user home directory as HOME
declare \
    real_home_dir
real_home_dir="$(
    getent \
        passwd \
        "${USER}" \
    | cut \
        --delimiter=: \
        --fields=6
)"
HOME="${real_home_dir}"

# Finally run the next part of the command chain
exec "${@}"
